"""add main_logs table

Revision ID: 515e11f8acd8
Revises: 
Create Date: 2025-01-22 12:24:16.130258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '515e11f8acd8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('app_name', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_main_logs_app_name'), 'main_logs', ['app_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_main_logs_app_name'), table_name='main_logs')
    op.drop_table('main_logs')
    # ### end Alembic commands ###
